framework:
    asset_mapper:
        # The paths to make available to the asset mapper.
        paths:
            - assets/
        missing_import_mode: strict
        server: true

when@prod:
    framework:
        asset_mapper:
            server: false
            missing_import_mode: warn
